sonar.projectKey=oriolsastre_PoolNET
sonar.organization=oriolsastre
sonar.projectBaseDir=.

sonar.sources=src/
sonar.tests=src/__tests__/

sonar.exclusions=src/__tests__/**/*,src/vendor/**/*,src/config/database.sql
sonar.tests.exclusions=src/__tests_/E2E/**/*

sonar.php.tests.reportPath=src/execution.xml
sonar.php.coverage.reportPaths=src/coverage.xml

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=PoolNET
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8