name: On Pull Request
on:
  pull_request:
    branches:
      - main
      - develop
    paths: "src/**"
    types: [opened, synchronize, reopened]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: PoolNET
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and seed database
        run: |
          cd ${{ github.workspace }}/src/config/database
          sqlite3 ${{ env.DB_DATABASE }}.db < database.sql
          sqlite3 ${{ env.DB_DATABASE }}.db < db_seed_test.sql
      - name: Rename env-example to env
        run: |
          cd ${{ github.workspace }}/src/config
          mv env-example.php Env.php
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug
      - name: Install dependencies with composer and run autoload
        run: |
          cd ${{ github.workspace }}/src
          composer update --no-ansi --no-interaction --no-progress
          cd ${{ github.workspace }}/src
          composer dump-autoload -o
      - name: Run tests with phpunit/phpunit
        run: |
          cd ${{ github.workspace }}/src
          vendor/bin/phpunit __tests__ --coverage-clover=coverage.xml --log-junit=execution.xml
      # - name: Fix code coverage paths
      #   run: |
      #     sed -i 's@'$GITHUB_WORKSPACE'@/home/runner/work/PoolNET/PoolNET@g' ${{ github.workspace }}/src/coverage.xml
      #     sed -i 's@'$GITHUB_WORKSPACE'@/home/runner/work/PoolNET/PoolNET@g' ${{ github.workspace }}/src/execution.xml
      - name: See coverage
        run: |
          cd ${{ github.workspace }}/src
          cat coverage.xml
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
