name: Backend on Pull Request
on:
  pull_request:
    branches:
      - main
      - develop
    paths: "back/**"
    types: [opened, synchronize, reopened]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: PoolNET
      DB_USER: root
      DB_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      - name: Build/Seed database
        run: mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < ${{ github.workspace }}/back/config/database.sql
      - name: Rename env-example to env
        run: |
          cd ${{ github.workspace }}/back/config
          mv env-example.php Env.php
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug
      - name: Install dependencies with composer
        run: |
          cd ${{ github.workspace }}/back
          composer update --no-ansi --no-interaction --no-progress
      - name: Run tests with phpunit/phpunit
        run: |
          cd ${{ github.workspace }}/back
          vendor/bin/phpunit __tests__ --coverage-clover=coverage.xml --log-junit=execution.xml
      # - name: Fix code coverage paths
      #   run: |
      #     sed -i 's@'$GITHUB_WORKSPACE'@/home/runner/work/PoolNET/PoolNET@g' ${{ github.workspace }}/back/coverage.xml
      #     sed -i 's@'$GITHUB_WORKSPACE'@/home/runner/work/PoolNET/PoolNET@g' ${{ github.workspace }}/back/execution.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
